dist: xenial
language: rust
stages:
  - Check
jobs:
  include:
    - stage: Check
      name: Format
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check
#    - stage: Check
#      name: Clippy
#      env: RUSTFLAGS='-F warnings'
#      script:
#        - rustup component add clippy
#        - cargo clippy --all --all-targets
